# yaml-language-server: $schema=https://raw.githubusercontent.com/not-first/glance-schema/master/schema.json
server:
  base-url: /glance

pages:
  - name: Home
    hide-desktop-navigation: true
    head-widgets:
      - type: search
        hide-header: true
        autofocus: true
    columns:
      - size: small
        widgets:
          - type: to-do
            hide-header: true
          - type: clock
            hide-header: true
            hour-format: 24h
            timezones:
              - timezone: Europe/Paris
                label: Paris
              - timezone: America/Guayaquil
                label: Quito
          - type: calendar
            hide-header: true
            first-day-of-week: monday
          - type: weather
            hide-header: true
            units: metric
            hour-format: 24h
            location: Quito, Ecuador
      - size: full
        widgets:
          - type: group
            hide-header: true
            widgets:
              - type: extension
                url: http://glance-custom-api:8081/youtube/latest
                cache: 1s
                allow-potentially-dangerous-html: true
              - type: extension
                url: http://glance-custom-api:8081/github/feed
                cache: 1s
                allow-potentially-dangerous-html: true
      - size: small
        widgets:
          - type: docker-containers
            hide-header: true
            containers:
              caddy:
                name: Caddy
                description: Home server Caddy proxy manager
                icon: di:caddy
                hide: false
              glance:
                name: Glance
                description: Home server dashboard with Glance
                url: http://glance.pi
                icon: di:glance
                hide: false
              grafana:
                name: Grafana
                description: Home server Grafana stats dashboard
                url: http://grafana.pi
                icon: di:grafana
                hide: false
              adguard:
                name: AdGuard
                description: Home server AdGuard DNS
                url: http://adguard.pi
                icon: mdi:shield-home
                hide: false
          - type: server-stats
            hide-header: true
            cache: 30s
            servers:
              - type: local
                name: Raspberry Pi
