name: caddy

services:
  caddy:
    container_name: caddy
    labels:
      glance.name: Caddy
      glance.icon: si:caddy
      glance.description: Caddy
    image: caddy:latest
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ../configs/caddy/Caddyfile:/etc/caddy/Caddyfile
      - /srv/caddy/data:/data
      - /srv/caddy/config:/config
    networks:
      - infra-network

networks:
  infra-network:
    external: true
