name: glance

services:
  glance:
    labels:
      glance.name: Glance
      glance.icon: di:glance
      glance.url: https://dietpi.tail00f31b.ts.net/glance
      glance.description: Glance dashboard
      glance.id: glance
    container_name: glance
    image: glanceapp/glance
    restart: unless-stopped
    ports:
      - 8080:8080
    volumes:
      - ../configs/glance:/app/config
    networks:
      - infra-network

networks:
  infra-network:
    external: true
