name: glance

services:
  glance:
    labels:
      glance.name: Glance
      glance.icon: di:glance
      glance.url: https://dietpi.tail00f31b.ts.net/glance
      glance.description: Glance dashboard
      glance.id: glance
    container_name: glance
    image: glanceapp/glance
    restart: unless-stopped
    ports:
      - 8080:8080
    volumes:
      - ../configs/glance:/app/config
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /proc/stat:/proc/stat:ro
      - /proc/meminfo:/proc/meminfo:ro
      - /proc/uptime:/proc/uptime:ro
      - /proc/loadavg:/proc/loadavg:ro
      - /sys/class/net:/sys/class/net:ro
      - /sys/block:/sys/block:ro
    networks:
      - infra-network

networks:
  infra-network:
    external: true
