name: pihole

services:
  pihole:
    container_name: pihole
    labels:
      glance.name: Pihole
      glance.icon: si:pihole
      glance.url: https://pihole.pi
      glance.description: Pihole
    image: pihole/pihole:latest
    platform: linux/arm/v7
    network_mode: host
    environment:
      TZ: America/Guayaquil
      DNSMASQ_LISTENING: all
      FTLCONF_webserver_port: "8080o,[::]:8080o,8443os,[::]:8443os"
      FTLCONF_dns_listeningMode: 'all'
    secrets:
      - pihole-password
    volumes:
      - /srv/pihole/etc-pihole:/etc/pihole
      - /srv/pihole/dnsmasq.d:/etc/dnsmasq.d
    restart: unless-stopped

secrets:
  pihole-password:
    file: ../secrets/pihole/pihole-password.txt
